general {
    lock_cmd = pidof hyprlock || ~/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# While hyprlock is running, turn the screen off after 60s of inactivity
listener {
    timeout = 60
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
